name: 🐠 Feature Request
description: Suggest an idea for this project
title: "[FEATURE REQUEST] <title>"
labels: ["Enhancement", "Question"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: Is your feature request related to a problem? Please describe.
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Behavior
    description: A clear and concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternative Solutions
    description: Describe alternatives you've considered.
    placeholder: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: dropdown
  id: godot_version
  attributes:
    label: Godot Version
    description: What version of Godot are you running?
    options:
      - 4.3.stable
      - 4.4.1.stable
      - 4.5.dev
      - 4.x
      - Other
    default: 1
  validations:
    required: true
- type: dropdown
  id: godot_os
  attributes:
    label: OS Godot Is Running On
    description: What operating system is Godot running on?
    options:
      - Windows 11
      - Windows (other)
      - macOS 15
      - macOS (other)
      - Android 14
      - Android (other)
      - Other OS
    default: 0
  validations:
    required: true
- type: dropdown
  id: plugin_version
  attributes:
    label: Plugin Version
    description: What version of the plugin are you running?
    options:
      - "3.0"
      - "3.1"
      - "3.2"
      - "3.3"
      - "4.0"
      - Other
    default: 4
  validations:
    required: true
- type: dropdown
  id: plugin_os
  attributes:
    label: OS Plugin Is Running On
    description: What operating system the plugin (and your app) is running on?
    options:
      - Android 12
      - Android 13
      - Android 14
      - Android (other)
    default: 2
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false